Rails.application.routes.draw do
  ## Generated by (rails g controller Home index) (we dont need)
  ##get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  ### Devise intialization instruction
  root to: "home#index"
  ##
  resources :albums do
    resources :images
  end
  
  devise_for :users
  
end
